name: 'Build and Deploy'

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release

jobs:
  build_deploy:
    name: 'Build and Deploy'
    runs-on: ubuntu-latest

    steps:
      #checkout
      - name: Checkout
        uses: actions/checkout@v3

      #Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      #Install
      - name: Install
        run: npm install

      #Build
      - name: Build
        run: npm run build

      - name: Creates 404 pages
        run: cp client/${{github.event.repository.name}}/index.html client/${{github.event.repository.name}}404.html

      #Deploy GitHub Pages
      - name: Deploy GH Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist